[package]
name = "trace_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
prettytable-rs = "0.9.0"
lazy_static = "1.4.0"
log = "0.4" 
ureq = "2.5.0"
