name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  new_release:
      runs-on: windows-latest
      outputs: 
        rel_uploadurl: ${{ steps.new_release.outputs.upload_url }}
      steps: 
      - 
        uses: actions/checkout@v3
      -
        uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: './Cargo.toml'
          field: 'package.version'
      -
        name: new_release 
        id: new_release
        uses: actions/create-release@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          tag_name: ${{steps.read_toml.outputs.value}}
          release_name: ${{steps.read_toml.outputs.value}}  
          draft: false 
          prerelease: false 
  build_win:
    runs-on: windows-latest
    needs: new_release
    steps:
    - 
      uses: actions/checkout@v3
    - 
      id: win_build
      run: cargo build --release --target=x86_64-pc-windows-msvc

    - 
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win_x64.zip target/x86_64-pc-windows-msvc/release/tracer-cli.exe
    - 
      name: upload win assets 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        upload_url: ${{ needs.new_release.outputs.rel_uploadurl }} 
        asset_path: win_x64.zip
        asset_content_type: application/zip
        asset_name: win-x64
      
  build_mac:
    runs-on: macos-latest
    needs: new_release
    steps: 
    - uses: actions/checkout@v3
    - 
      name: Build
      id: mac-build
      run: |
        cargo build --release --target=x86_64-apple-darwin
        rustup target add aarch64-apple-darwin
        cargo build --release --target=aarch64-apple-darwin
    - 
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r mac-intel64.zip target/x86_64-apple-darwin/release/tracer-cli
    - 
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r mac-arm64.zip target/aarch64-apple-darwin/release/tracer-cli
    - 
      name: upload mac64 assets 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        upload_url: ${{  needs.new_release.outputs.rel_uploadurl }} #
        asset_path: mac-intel64.zip
        asset_name:  mac-intel64.zip
        asset_content_type: application/zip
    - 
      name: upload mac-arm assets 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        upload_url: ${{  needs.new_release.outputs.rel_uploadurl }} #
        asset_path: mac-arm64.zip
        asset_name: mac-arm64.zip
        asset_content_type: application/zip
